declare module "lucide-react" {
  import type { FC, SVGProps } from "react"
  interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    absoluteStrokeWidth?: boolean
  }
  type Icon = FC<LucideProps>
  export type LucideIcon = Icon
  export const ArrowRight: Icon
  export const ArrowRightCircle: Icon
  export const ArrowUpRight: Icon
  export const Award: Icon
  export const BadgeCheck: Icon
  export const Beaker: Icon
  export const Calculator: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronUp: Icon
  export const ClipboardCheck: Icon
  export const Clock: Icon
  export const Coins: Icon
  export const Copy: Icon
  export const Download: Icon
  export const Droplet: Icon
  export const Edit3: Icon
  export const ExternalLink: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Facebook: Icon
  export const Factory: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const FlaskConical: Icon
  export const Globe: Icon
  export const Grid: Icon
  export const Hash: Icon
  export const Headphones: Icon
  export const Headset: Icon
  export const Heart: Icon
  export const HeartHandshake: Icon
  export const HelpCircle: Icon
  export const Home: Icon
  export const Image: Icon
  export const Info: Icon
  export const Instagram: Icon
  export const Layers: Icon
  export const Lightbulb: Icon
  export const Link: Icon
  export const Linkedin: Icon
  export const List: Icon
  export const Lock: Icon
  export const LogIn: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Maximize2: Icon
  export const Megaphone: Icon
  export const Menu: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const Minimize2: Icon
  export const Minus: Icon
  export const MoreHorizontal: Icon
  export const MoreVertical: Icon
  export const Package: Icon
  export const PackageCheck: Icon
  export const Palette: Icon
  export const Pause: Icon
  export const Phone: Icon
  export const Play: Icon
  export const Plus: Icon
  export const RefreshCw: Icon
  export const RotateCw: Icon
  export const Save: Icon
  export const Scale: Icon
  export const Search: Icon
  export const Send: Icon
  export const Settings: Icon
  export const Share2: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const ShoppingBag: Icon
  export const Sliders: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Sun: Icon
  export const Tag: Icon
  export const Target: Icon
  export const ThumbsUp: Icon
  export const Trash2: Icon
  export const TrendingUp: Icon
  export const Truck: Icon
  export const Twitter: Icon
  export const Upload: Icon
  export const User: Icon
  export const Users: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Wallet: Icon
  export const Waves: Icon
  export const X: Icon
  export const Youtube: Icon
  export const Zap: Icon
}
