// Generator: src/data/site-paths.ts — daftar path valid untuk middleware 404.
// Di-run via tsx agar bisa impor data asli (robust, bukan regex).
import fs from 'fs';
import path from 'path';
import { articles } from '@/data/articles';
import { maklonPages } from '@/data/maklon-pages';
import { productDataV2 } from '@/data/products-v2';
import seoMapping from '@/data/seo-mapping.json';

const root = path.resolve(__dirname, '..');
const valid = new Set<string>();
const add = (p: string) => { const s = p.replace(/^\/+/, '').replace(/\/+$/, ''); if (s) valid.add(s); };

// 1. Static routes (rute tetap + ads/metaads/landing/thankyou yang 200)
const staticRoutes = [
  '', '/news-blog', '/panduan', '/about-us', '/about-us/alur-maklon',
  '/services', '/contact-us', '/contact-medsos', '/our-client', '/career',
  '/terms-of-service', '/privacy-policy', '/estimasi-biaya-maklon-kosmetik',
  '/biaya-maklon-skincare', '/moq-maklon-kosmetik', '/jasa-maklon-kosmetik',
  '/private-label-kosmetik', '/lead-test', '/landing/mof-bof',
  '/ads/maklon-body-care', '/ads/maklon-hair-care', '/ads/maklon-parfum', '/ads/maklon-skincare',
  '/ads/thankyou/google', '/ads/thankyou/google-ads', '/ads/thankyou/metaads', '/ads/thankyou-medsos',
  '/google-ads/maklon-body-care', '/google-ads/maklon-hair-care',
  '/google-ads/maklon-kosmetik', '/google-ads/maklon-parfum',
  '/metaads/babycare', '/metaads/deodorant', '/metaads/haircare',
  '/metaads/parfum', '/metaads/skincare',
  '/hair-care/metaads', '/parfum/metaads', '/skincare-face-care/metaads',
  '/thankyou/google', '/thankyou-medsos',
  '/panduan/cara-menentukan-moq-produk-kosmetik',
  '/panduan/komponen-biaya-maklon-skincare',
  '/category/maklon-kosmetik', '/category/panduan-bisnis-kosmetik',
  '/category/dreampreneur-beauty-academy',
  '/produk',
  '/en', '/en/produk', '/en/about-us', '/en/services', '/en/our-client', '/en/contact-us',
];
staticRoutes.forEach(add);

// 2. Artikel
articles.forEach(a => { if (a.slug) add(a.slug); });

// 3. Maklon pages — SEMUA path maklonPages disertakan.
//    Beberapa maklon page memang redirect (skincare/parfum/baby-care via
//    LEGACY_SLUG_REDIRECTS di proxy), tapi yang lain (body-care, hair-care,
//    foot-care, decorative) SERVE KONTEN 200 via catch-all. Middleware menangani
//    redirect TERLEBIH DAHULU, lalu SITE_PATHS hanya mengecek path yang tersisa.
//    Jadi semua maklonPages wajib ada di SITE_PATHS agar yang serve tidak 404.
maklonPages.forEach(p => add(p.path));

// 4. seo-mapping destinations
(seoMapping as Array<{ destination?: string }>).forEach(m => { if (m.destination) add(m.destination); });

// 5. Produk pages — SEMUA level (kategori, sub-kategori, produk flat, produk sub-kategori)
for (const [cat, catData] of Object.entries(productDataV2)) {
  add(`produk/${cat}`);
  // Produk flat (top-level)
  catData.products.forEach(p => add(`produk/${cat}/${p.slug}`));
  // Sub-kategori + produk di dalamnya
  if (catData.subCategories) {
    for (const sub of catData.subCategories) {
      add(`produk/${cat}/${sub.slug}`);
      sub.products.forEach(p => add(`produk/${cat}/${sub.slug}/${p.slug}`));
    }
  }
}

// 6. author & news-blog pagination
add('author/admin');
for (let i = 2; i <= 12; i++) {
  add(`author/admin/page/${i}`);
  add(`news-blog/page/${i}`);
  add(`page/${i}`);
}

const list = Array.from(valid).filter(Boolean).sort();
const out = `// GENERATED by scripts/generate-site-paths.ts — DO NOT EDIT MANUALLY.\n// Regenerate: npm run gen:paths (otomatis saat prebuild).\nexport const SITE_PATHS: string[] = ${JSON.stringify(list, null, 2)};\n`;
fs.writeFileSync(path.join(root, 'src/data/site-paths.ts'), out, 'utf-8');
console.log(`Generated ${list.length} valid paths -> src/data/site-paths.ts`);
